### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [puppetlabs/rust-kitchensink#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by MikaelSmith** [comment]
This library is not currently being maintained and is being archived. If you find it useful, you can get in touch with us via other avenues at https://puppet.com/community to discuss ways to migrate it to new ownership.
